apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      name: mssql
      labels:
        app: mssql
    spec:
      containers:
        - name: main
          image: mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-16.04
          env:
            - name: SA_PASSWORD
              value: P@ssw0rd
            - name: ACCEPT_EULA
              value: "Y"
          ports:
            - containerPort: 1433
          readinessProbe:
            exec:
              command: ["/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "P@ssw0rd", "-Q", "SELECT 1", "GO"]
            initialDelaySeconds: 15
            timeoutSeconds: 2
      nodeSelector:
        kubernetes.io/os: linux